import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import DashboardSidebar from "./components/DashboardSidebar";
import Navbar from "./components/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Inkril Books",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased h-screen`}
      >
        <div className="flex h-full">
          {/* Sidebar */}
          <DashboardSidebar />

          {/* Main content area */}
          <div className="flex flex-col flex-1 min-h-full">
            {/* Navbar at the top */}
            <Navbar />

            {/* Page content fills the rest */}
            <main className="flex-1 overflow-auto bg-white p-6">
              {children}
            </main>
          </div>
        </div>
      </body>
    </html>
  );
}
